// 遊戲資源建議加上遊戲前綴 ex: brnn => brnn_bg, brnn_table
const ImageRes = {
    //png.jpg範例: game_bg: require('../../res/i/background/game_bg.png')
    game_bg_start: require('../../res/i/bg_board/bg_start.png'),
    btn_play: require('../../res/i/button/btn_play.png'),
    btn_music_on: require('../../res/i/button/btn_musicon.png'),
    btn_shop: require('../../res/i/button/btn_shop.png'),
    btn_achievement: require('../../res/i/button/btn_achievement.png'),
    btn_tutorial: require('../../res/i/button/btn_tutorial.png'),
    logo: require('../../res/i/bg_board/logo.png'),
    bg_game: require('../../res/i/bg_board/bg_game.png'),
    btn_pause: require('../../res/i/button/btn_pause.png'),
    img_transition: require('../../res/i/bg_board/img_transition.png'),
    text_time: require('../../res/i/other/text_time.png'),
    text_stage: require('../../res/i/other/text_stage.png'),
    bg_tutorial: require('../../res/i/bg_board/bg_tutorial.png'),
    btn_cancel: require('../../res/i/button/btn_cancel.png'),
    btn_unuse: require('../../res/i/button/btn_unuse.png'),
    btn_right: require('../../res/i/button/btn_right.png'),
    btn_left: require('../../res/i/button/btn_left.png'),
    img_tutorialA: require('../../res/i/other/img_tutorial1.png'),
    img_tutorialB: require('../../res/i/other/img_tutorial2.png'),
    btn_music_off: require('../../res/i/button/btn_musicoff.png'),
    img_lightwhite: require('../../res/i/tilemap_image/img_lightwhite.png'),
    tile_1: require('../../res/i/tilemap_image/tile_1.png'),
    tile_2: require('../../res/i/tilemap_image/tile_2.png'),
    tile_3: require('../../res/i/tilemap_image/tile_3.png'),
    tile_4: require('../../res/i/tilemap_image/tile_4.png'),
    tile_5: require('../../res/i/tilemap_image/tile_5.png'),
    tile_6: require('../../res/i/tilemap_image/tile_6.png'),
    tile_7: require('../../res/i/tilemap_image/tile_7.png'),
    tile_8: require('../../res/i/tilemap_image/tile_8.png'),
    tile_9: require('../../res/i/tilemap_image/tile_9.png'),
    tile_10: require('../../res/i/tilemap_image/tile_10.png'),
    tile_11: require('../../res/i/tilemap_image/tile_11.png'),
    tile_12: require('../../res/i/tilemap_image/tile_12.png'),
    tile_13: require('../../res/i/tilemap_image/tile_13.png'),
    tile_14: require('../../res/i/tilemap_image/tile_14.png'),
    tile_15: require('../../res/i/tilemap_image/tile_15.png'),
    tile_16: require('../../res/i/tilemap_image/tile_16.png'),
    tile_17: require('../../res/i/tilemap_image/tile_17.png'),
    tile_18: require('../../res/i/tilemap_image/tile_18.png'),
    tile_19: require('../../res/i/tilemap_image/tile_19.png'),
    tile_20: require('../../res/i/tilemap_image/tile_20.png'),
    img_endmark_1: require('../../res/i/tilemap_image/img_endmark_1.png'),
    img_mainrole_idle_11: require('../../res/i/tilemap_image/img_mainrole_idle1_1.png'),
    img_mainrole_idle_12: require('../../res/i/tilemap_image/img_mainrole_idle1_2.png'),
    img_mainrole_idle_21: require('../../res/i/tilemap_image/img_mainrole_idle2_1.png'),
    img_mainrole_idle_22: require('../../res/i/tilemap_image/img_mainrole_idle2_2.png'),
    img_mainrole_idle_31: require('../../res/i/tilemap_image/img_mainrole_idle3_1.png'),
    img_mainrole_idle_32: require('../../res/i/tilemap_image/img_mainrole_idle3_2.png'),
    img_mainrole_idle_41: require('../../res/i/tilemap_image/img_mainrole_idle4_1.png'),
    img_mainrole_idle_42: require('../../res/i/tilemap_image/img_mainrole_idle4_2.png'),
    img_mainrole_idle_51: require('../../res/i/tilemap_image/img_mainrole_idle5_1.png'),
    img_mainrole_idle_52: require('../../res/i/tilemap_image/img_mainrole_idle5_2.png'),
    img_mainrole_idle_61: require('../../res/i/tilemap_image/img_mainrole_idle6_1.png'),
    img_mainrole_idle_62: require('../../res/i/tilemap_image/img_mainrole_idle6_2.png'),
    board_pause: require('../../res/i/bg_board/board_pause.png'),
    btn_home: require('../../res/i/button/btn_home.png'),
    btn_continue: require('../../res/i/button/btn_continue.png'),
    text_stagehis: require('../../res/i/other/text_stagehis.png'),
    board_result: require('../../res/i/bg_board/board_result.png'),
    btn_replay: require('../../res/i/button/btn_replay.png'),
    board_shop: require('../../res/i/bg_board/board_shop.png'),
    btn_onuse: require('../../res/i/button/btn_onuse.png'),
    img_mainrole_move_11: require('../../res/i/tilemap_image/img_mainrole1_1.png'),
    img_mainrole_move_12: require('../../res/i/tilemap_image/img_mainrole1_2.png'),
    img_mainrole_move_21: require('../../res/i/tilemap_image/img_mainrole2_1.png'),
    img_mainrole_move_22: require('../../res/i/tilemap_image/img_mainrole2_2.png'),
    img_mainrole_move_31: require('../../res/i/tilemap_image/img_mainrole3_1.png'),
    img_mainrole_move_32: require('../../res/i/tilemap_image/img_mainrole3_2.png'),
    img_mainrole_move_41: require('../../res/i/tilemap_image/img_mainrole4_1.png'),
    img_mainrole_move_42: require('../../res/i/tilemap_image/img_mainrole4_2.png'),
    img_mainrole_move_51: require('../../res/i/tilemap_image/img_mainrole5_1.png'),
    img_mainrole_move_52: require('../../res/i/tilemap_image/img_mainrole5_2.png'),
    img_mainrole_move_61: require('../../res/i/tilemap_image/img_mainrole6_1.png'),
    img_mainrole_move_62: require('../../res/i/tilemap_image/img_mainrole6_2.png'),
    board_talk: require('../../res/i/bg_board/board_talk.png'),
};

// 存取key值方便直接關聯調用, 也可存取合圖裡的key值
// 建議多張圖直接存取一組key值, 後續在調用string-format來拼接, ex: card_0: 'card_0', card_1: 'card_1'.... => card: 'card_{0}'
export const ImageKey = {
    game_bg_start: 'game_bg_start',
    btn_play: 'btn_play',
    btn_music_on: 'btn_music_on',
    btn_music_off: 'btn_music_off',
    btn_shop: 'btn_shop',
    btn_achievement: 'btn_achievement',
    btn_tutorial: 'btn_tutorial',
    logo: 'logo',
    bg_game: 'bg_game',
    btn_pause: 'btn_pause',
    img_transition: 'img_transition',
    text_time: 'text_time',
    text_stage: 'text_stage',
    bg_tutorial: 'bg_tutorial',
    btn_cancel: 'btn_cancel',
    btn_unuse: 'btn_unuse',
    btn_right: 'btn_right',
    btn_left: 'btn_left',
    img_tutorialA: 'img_tutorialA',
    img_tutorialB: 'img_tutorialB',
    img_lightwhite: 'img_lightwhite',
    tile: 'tile_{0}',
    img_endmark_1: 'img_endmark_1',
    img_mainrole_idle: 'img_mainrole_idle_{0}',
    img_mainrole_move: 'img_mainrole_move_{0}',
    board_pause: 'board_pause',
    btn_home: 'btn_home',
    btn_continue: 'btn_continue',
    text_stagehis: 'text_stagehis',
    board_result: 'board_result',
    btn_replay: 'btn_replay',
    board_shop: 'board_shop',
    btn_onuse: 'btn_onuse',
    board_talk: 'board_talk',
};

const SoundRes: any = [
    // 音檔讀取規則 { n: 'game_bgm', f: require('../../res/a/game_bgm.mp3') },
    { n: 'sound_maintheme', f: require('../../res/a/sound_maintheme.mp3') },
    { n: 'sound_tap_tile', f: require('../../res/a/sound_tap_tile.mp3') },
    { n: 'sound_btn', f: require('../../res/a/sound_btn.mp3') },
    { n: 'sound_cancel', f: require('../../res/a/sound_cancel.mp3') },
    { n: 'sound_putit', f: require('../../res/a/sound_putit.mp3') },
    { n: 'sound_bird', f: require('../../res/a/sound_bird.mp3') },
    { n: 'sound_gameclear', f: require('../../res/a/sound_gameclear.mp3') },
    { n: 'game_gameclear2', f: require('../../res/a/game_gameclear2.mp3') },
];

// 存取key值方便直接關聯調用
export const SoundKey = {
    sound_maintheme: 'sound_maintheme',
    sound_tap_tile: 'sound_tap_tile',
    sound_btn: 'sound_btn',
    sound_cancel: 'sound_cancel',
    sound_putit: 'sound_putit',
    sound_bird: 'sound_bird',
    sound_gameclear: 'sound_gameclear',
    game_gameclear2: 'game_gameclear2',
};

export const Assets = {
    main: ImageRes,
    audio: SoundRes
};
