export const GameEvent = {
    CHANGE_VIEW: 'CHANGE_VIEW',
    CHANGE_GAME_STATR: 'CHANGE_GAME_STATR',
    CONTINUE_GAME: 'CONTINUE_GAME',
    PAUSE_GAME: 'PAUSE_GAME',
    CHANGE_BIRD_SKIN: 'CHANGE_BIRD_SKIN',
};